### ISSUE TITLE
clean up the build system into a lib subdir

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#10]
It is not easy to find which things to edit here. 
Can we put all the build system resources (xslts, ... ) into a `lib` subdir? 
And document that in the README?

**Comment by davidcarlisle** [comment]
actually the main problem that there were over 20 generated files that were checked in (presumably from checking in an old build area) I deleted these and moved the xsl down a level. No time today to make the various scripts use different local paths so I made top level run script copy everything into a build subdirectory, has advantage that if you build locally tex log and aux files and temp files made while converting schema are all left in ./build.

**Comment by kohlhase** [comment]
this looks much much better; I like the `build`-based system. 
Thanks. I have updated the README for that. 
There are two things I would do: 
* move `install-jars` into `support1`
* take the automatic installation of texlive (most have it already and it is _big_) ouf of it.

**Comment by davidcarlisle** [comment]
I'd assumed that only travis would use install-jars (and it does need to install texlive as it isn't installed in the default VM) however I have now  guarded the texlive bit by `if [ "$TRAVIS" = "true" ]; then`  so it won't install that  if run by hand. Note however if you don't have texlive 2017 then you will almost certainly get binary differences in the pdf file and so create extra diffs in the OpenMath.gihub.io repo if you build locally and copy the generated files to your local checkout. However I've just checked again just now that if you use the saxon and trang jars as fetched by install-jars, and a stock texlive2017 then ./run in OMSTD regenerates all of om20-editors-draft in OpenMath.github.io with no diffs.

**Comment by davidcarlisle** [comment]
I think that's as clean as it's going to get, closing.
