### ISSUE TITLE
run script does not run for me

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#11]
I get the following erros (on MacOS)

```
Michaels-MBP-3:OMSTD kohlhase$ ec run 
Waiting for Emacs...^C
Michaels-MBP-3:OMSTD kohlhase$ source ./run 
TARGET=om20-editors-draft
date: illegal option -- -
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...91 completed.

[Process completed]
```

**Comment by davidcarlisle** [comment]
hmm  `source ./run` or more simply just `./run`  (as executable bit set) work for me, and also work on travis.

and I haven't got a mac to debug on...

I assume it fails on

```
DATE=`date --iso`
```

could you just replace that by

DATE=2017-09-30

and see if that works for you, going forward what works on the mac that does the equivalent of

```
$ date --iso
2017-09-30
```

**Comment by kohlhase** [comment]
indeed that seems to be the problem
```
date "+%Y-%m-%d"
```
does that work for you as well?
