### ISSUE TITLE
Update to new URI spec 

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#29]
Reference to RFC 2396 is obsolete, we should point to RFC 3986 and remove the note about fancy encoding (since the newer one suggests UTF-8).

see https://github.com/OpenMath/OM3/issues/9

**Comment by kohlhase** [comment]
This is something David and I could do quite quickly.

**Comment by JamesHDavenport** [comment]
Please do.
James

**Comment by kohlhase** [comment]
just for reference, the paragraph in question is 

>CD Base  A cdbase must conform to the grammar for URIs described in [7]. Note that if non-ASCII characters are used in a CD or symbol name then when a URI for that symbol is constructed it will be necessary to map the non-ASCII characters to a sequence of octets. The precise mechanism for doing this depends on the URI scheme.

in section **2.3 Names** of the standard. and [7] is the reference to RFC 2396. 

I am wondering whether we should directly go to adopting and referencing IRIs (i.e. RFC 3987) here.

**Comment by davidcarlisle** [comment]
yes I think we should ref 3987.

It's such a mess: the xml spec defines its usage of URI but then predicts the future 

>  IETF RFC 3987, which will define "Legacy Extended IRIs (LEIRIs)". When this revision is available, it is the intent of the XML Core WG to use it to replace language similar to the above in any future revisions of XML-related specifications under its purview

but 3987 does not define LEIRI and the whole area is a complete minefield.

whatwg essentially abandoned the whole stack of ur[lin]* specifications from w3c/ietc and  produced a unified URL spec that actually matches what happens in the wild

https://url.spec.whatwg.org/

That said, we don't need to specify actual processing so I think 3987 is the place we should reference as OpenMath references are traditionally to ietf/w3c/iso specs.

**Comment by davidcarlisle** [comment]
I seemed to have failed to make the link automatically but there is a pull request

https://github.com/OpenMath/OMSTD/pull/50

for review to address this issue

**Comment by kohlhase** [comment]
I think we should continue discussion on #50
