### ISSUE TITLE
CD versioning probably not compatible with CD URIs

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#43]
see https://github.com/OpenMath/OM3/issues/126

**Comment by davidcarlisle** [comment]
I'm not sure what we can offer here that is more convenient to the existing web access to the git history (for any versions going forward) (of course the original issue was posted before we had the source control history online)

It would be possible to use something such as 

https://openmath.github.io/cd/arith1?version=xxx

with some javascript in the generated arith1.html that redirects or simpler a conventional name such as

https://openmath.github.io/cd/arith1-versionxxxx

with a redirect file of that name

but either would need to be documented and implemented and wouldn't be as flexible as pointing at the version history at

https://github.com/OpenMath/CDs/commits/master/cd/Official/arith1.ocd

This is similar in many ways to tex packages and other things, the package advertises its version number which is a useful debugging information if things go wrong but older versions are not accessible via general mechanisms you need to find an archived installation to access old copies.  More commonly the flow is the other way the version number just used to inform the user that their local copy is out of date and a newer bug fixed version is available on the web.

**Comment by kohlhase** [comment]
I believe that Christoph Lange was thinking along the lines of 

> https://openmath.github.io/cd/arith1?version=xxx

independently of how (and if) that can be implemented. But I agree with you that we can alrady now do that: 
https://github.com/OpenMath/CDs/blob/1b65014409fccc58fe774bab80233f234652746c/cd/Official/arith1.ocd
points to the version of `arith1.ocd` as it was between July 26. and September 30. 2017. Thus we can even use that in an OMS:
```XML
<OMS cd="arith1" name="plus 
cdbase="https://github.com/OpenMath/CDs/blob/1b65014409fccc58fe774bab80233f234652746c/cd/Official/"/>
```
Right, so there is probably nothing to do. This may be something we want to document, e.g. in the FAQ. If you agree, I can do that. 

We could (in the future; based on this mechanism) build a github-metadata-based service that redirects the nice  https://openmath.github.io/cd/arith1?version=xxx to the ugly github URI, but that is definitely future work and should not be baked into the standard.

**Comment by kohlhase** [comment]
I am assigning myself and also James, since I definitely want his opinion on this.
