### ISSUE TITLE
note about hex byte ordering

### ISSUE THREAD

**Issue by davidcarlisle** [OpenMath/OMSTD#49]
2.0r1 adds a note saying that the wording

from lowest to highest bits using a least significant byte ordering

is copied from MathML, but essentially the same wording was in the om 1 spec

https://openmath.github.io/standard/om10/omstd.pdf

**Comment by kohlhase** [comment]
OK, then this issue is already fixed. Thanks for noticing.

**Comment by davidcarlisle** [comment]
Not sure why this got closed, I was commenting on text that was added at 2.0r1

**Comment by kohlhase** [comment]
sorry, I misread this. 

So you are sugesting that we drop the "copied" rhethoric?

**Comment by davidcarlisle** [comment]
yes we say we copied "meaningless text" from another spec which reads a bit
odd, and to make it worse, the text in question originated in the openmath
spec!

anyway so I thought I'd complain (although whether I'm the offender or the
offended depends which hat I'm wearing:-)

**Comment by kohlhase** [comment]
whatever the hat is you are wearing, you are probably uniquely suited to patch up the situation for OM2r2.
