### ISSUE TITLE
foreign objects not described in "3.1.2 Informal description of the XML Encoding"

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#58]
**3.1.2** does not have a description of foreign objects, but **3.2.2 Description of the Grammar** [of the binary encoding] does. Instead there is a discussion of the Foreign Objects (in the XML encoding) in **5.2 OpenMath Foreign Objects**. 

To me this is a mess-up in the systematics of the description. I am not sure how to fix this. 

Could we just move 5.2 into 3.1.2? Otherwise we should probably have a forward reference under 3.1.2 into 5.2.

What do you think? 

I would think that merely moving a paragraph would be "editorial".

**Comment by davidcarlisle** [comment]
foreign objects are described in section 3.1.2 under the entry for attribution.

This is consistent with the entry for basic objects in 2.1.1 which says

> . (Note that derived OpenMath objects are not OpenMath objects, but are used to construct OpenMath objects as described below.)

that is OMFOREIGN does not construct an openmath object but just a second class citizen that can live in attributions and errors.

**Comment by JamesHDavenport** [comment]
IT seems to me as if David has the answer,unless I am wrong.

**Comment by kohlhase** [comment]
Oh, you are right, I have added a varlistentry to make this more regular.
