### ISSUE TITLE
there seems to be no uniqueness requirement for CD names in a CDGroup

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#60]
#57 (and MathML3) suggest the use of CDGroup files as "catalogs" as default for `cdbase`. BUT there does not seem to be a uniqueness requirement for `CDGroupMember/CDName` in `CDGroup`. 
This is consistent with the use of CDGroup files for declaring "the set of CDs my application understands" as envisioned in the standard but not with the use of a catalog for `cdbase`. 
 
So if we want to adopt #57 in OM2r2 (which would be very good for MathML3 alignment), I guess we also have to add some language about "Catalog" in the intro of **4.2 CDGroups** and add a uniqueness constraint in **4.4.2.2 Further Requirements of a CDGroup**/CDName.

**Comment by kohlhase** [comment]
I just checked, all the CDgroups we currently have seem to obey the uniqueness constraint, so we probably do not need to worry about backwards compatibility.

**Comment by davidcarlisle** [comment]
It  may not be spelt out explicitly but a cdgroup with the same cdname
mapped to two different url is just internally inconsistent under any
interpretation of cdgroups isn't it?

It's defined as an unordered list of cds, indexed by name (and optional url
and version) so I think that implies (although could be stated more
explicitly) that the names have to be unique

**Comment by kohlhase** [comment]
> It  may not be spelt out explicitly but a cdgroup with the same cdname
> mapped to two different url is just internally inconsistent under any
> interpretation of cdgroups isn't it?

Actually,  one could argue that unter the interpretation "My system can understand all these CDs" it is not inconsistent, even if there are two CDs with the same name (given that all symbols have an explicit "cdname"). But I would consider that a fundamentalist's view and not "common intuition". 

I certainly always had the intuition that CDNames have to be unique in a CDGroup (and was thus surprised to not see it spelt out in the standard). 

Therefore I think that we can and should clarify the uniqueness constraint with much the words you propose above. 

Let me start working on a a pull request that does that and also incorporates  #57 my proposed solution for #59. And then we can see whether we can fold in something for #45 as well.

**Comment by kohlhase** [comment]
OK, I have started that in PR #61, currrently only the stuff for #57

**Comment by kohlhase** [comment]
solved in PR #61
