### ISSUE TITLE
run script copies generated files to website when not in travis (and on a branch)

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#62]
I ran `run` on my `alpha-conversion` branch  and got 
```
[...]
zip
copying documents to ../OpenMath.github.io/standard/om20-editors-draft
Michaels-MBP-3:OMSTD kohlhase$ git branch
* alpha-conversion
  cdgroups
  master
  xref-href
Michaels-MBP-3:OMSTD kohlhase$ cd ../OpenMath.github.io/
Michaels-MBP-3:OpenMath.github.io kohlhase$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   standard/om20-editors-draft/omcdgroup2.dtd
	modified:   standard/om20-editors-draft/omcdgroup2.rnc
	modified:   standard/om20-editors-draft/omcdgroup2.rng
	modified:   standard/om20-editors-draft/omcdgroup2.xsd
	modified:   standard/om20-editors-draft/omstd20-diff.html
	modified:   standard/om20-editors-draft/omstd20-diff.pdf
	modified:   standard/om20-editors-draft/omstd20.html
	modified:   standard/om20-editors-draft/omstd20.pdf
	modified:   standard/om20-editors-draft/openmath2.dtd
	modified:   standard/om20-editors-draft/openmath2.rnc
	modified:   standard/om20-editors-draft/openmath2.rng
	modified:   standard/om20-editors-draft/openmath2.xsd

no changes added to commit (use "git add" and/or "git commit -a")
Michaels-MBP-3:OpenMath.github.io kohlhase$ 
```
This should not happen.

**Comment by davidcarlisle** [comment]
shouldn't it happen?, why not?

if travis is running it only copies and commits if running from master

if run locally and a sibling ../Openmath.github.io  exists it always copies
but never tries to commit.

I find that useful as you can check that the change that you intended to
make in the branch shows up in the generated html.

just do git checkout -- standard  and clean up the OpenMath,github.io repo
even if you run locally from the master branch you usually have to do
checkout --standard to clean up as you will get differences in build date
etc which will leave local copies blocking a git pull.

**Comment by kohlhase** [comment]
hmmm, it was unexpected to me, therefore I thought it may have been an oversight :-). 
I always look at the local version under `build` to see the changes I am making. That feels safer to me. 
But I can work with your version as well.  Feel free to close.

**Comment by davidcarlisle** [comment]
well... it was intentional to copy but actually It predates the travis
setup so done with the intention that you'd push from the local copy. I may
make it not  copy by default. leave it open for a bit I may come back to
this...
