### ISSUE TITLE
href or xref?

### ISSUE THREAD

**Issue by lars-hellstrom** [OpenMath/OMSTD#7]
[Section 3.1.3.1 of the standard](https://openmath.github.io/standard/om20-2017-07-22/omstd20.html#sec_acyclicity) uses `xref` (with no `#` before the fragment identifier) as the attribute of `OMR`. The RNG schema says it should be `href`, and that the value is an URI.

This was previously reported in: OpenMath/OM3#104

**Comment by davidcarlisle** [comment]
the wording of the standard explicitly says href and says it takes a URI see the description of references and the example in figure 3.1, looks like the example in 3.1.3.1 got missed (this attribute oscillated between href and xref in earlier drafts as I recall)

**Comment by kohlhase** [comment]
Actually, the RNC in 3.1.1 and the "informal description" in 3.1.2 use `href` consistently and a `#` in the fragment identifier , and then 3.1.3 uses `xref` and no `#` consistently in all examples and the text. 
What a mess. I think we should just stick with `xref` and `#` and clean up 3.1.3. 
I will do that and make a pull request. 
cc: @JamesHDavenport

**Comment by davidcarlisle** [comment]
@kohlhase  no I think the intended scheme is to use href and a uri which is used everywhere except for 6 bad instances of "xref" in the spec.

**Comment by davidcarlisle** [comment]
see also all uses of OMR in the CDs which all consistently use href
```

$ grep  -o '<OMR[^<>]*' */*/*ocd 
cd/experimental/field3.ocd:<OMR href="#pr"/
cd/experimental/field3.ocd:<OMR href="#prn"/
cd/experimental/field4.ocd:<OMR href="#pr"/
cd/experimental/field4.ocd:<OMR href="#pr"/
cd/experimental/linalgeig1.ocd:<OMR href="#pr"/
cd/experimental/linalgeig1.ocd:<OMR href="qr"/
cd/experimental/linalgeig2.ocd:<OMR href="#ev"/
cd/experimental/polynomial3.ocd:<OMR href="#pr"/
cd/experimental/polynomial3.ocd:<OMR href="#r"/
cd/experimental/ring3.ocd:<OMR href="#domain"/
cd/experimental/ringname1.ocd:<OMR href="#fr"/
cd/Official/scscp1.ocd:<OMR href="scscp://somehost:26133/92cfceb39d57d914ed8b14d0e37643de0797ae56"/
cd/Official/scscp1.ocd:<OMR href="scscp://somehost.somedomain:26133/q9t4eX"/
cd/Official/scscp2.ocd:<OMR href="scscp://somewhere:26133/qjhtkoeurthoedu"/
cd/Official/scscp2.ocd:<OMR href="scscp://somewhere:26133/qjhtkoeurthoedu"/
cd/Official/scscp2.ocd:<OMR href="scscp://somewhere:26133/qjhtkoeurthoedu"/

```

**Comment by kohlhase** [comment]
> What a mess. I think we should just stick with xref and # and clean up 3.1.3.

Oh, I am still contributing to the mess, I wanted to say "stick with `href` and ...."

**Comment by davidcarlisle** [comment]
@kohlhase  or did you mean "stick with _href_ and `#` ?

**Comment by davidcarlisle** [comment]
Ah OK then yes agreed:-)

**Comment by kohlhase** [comment]
yes, see PR #12

**Comment by kohlhase** [comment]
closing here in favor of #12.
