### ISSUE TITLE
make sure that only master is pushed to the web site

### ISSUE THREAD

**Issue by kohlhase** [OpenMath/OMSTD#9]
David, you made sure that only the `master` branch is pushed to the web site. I think we need this for this repos as well.

**Comment by davidcarlisle** [comment]
OK I handled it differently here. I just turned off travis build for branches and PR

https://travis-ci.org/OpenMath/OMSTD/settings

The CDs build is more technical (and we might more likley get pull requests to add cds) so there I let travis do the build (so any failure gets notified) but it just skips the final step of pushing to the website. I could do same here but turning off seems safe enough, building a document and then deleting the VNM before showing the doc to anyone doesn't seem that useful.

**Comment by kohlhase** [comment]
excellent, thanks.

**Comment by davidcarlisle** [comment]
I should have known, master branch is a branch.. so telling travis not to build on branch commits isn't the right thing to so....

I reverted that setting and added an environment variable check as in CDs  repo.

so on a branch (unless you modify the travis settings or run script in that branch) travis will build the document but not copy it to the website.

**Comment by davidcarlisle** [comment]
reopened for the record but this is fixed now, so closing.
